#!/usr/bin/python3
a = input('Введите число 1: ')
b = input('Введите число 2: ')
c = float(a) + float(b)
print('Результат сложения:', c)
d = float(a) - float(b)
print('Результат вычетания:', d)
e = float(a) * float(b)
print('Результат умножения:', e)
f = float(a) / float(b)
print('Результат деления:', f)
g = float(a) ** float(b)
print('Результат возведения в степень:', g)
k = float(a) // float(b)
print('Результат целочисленного деления:', int(k))
l = float(a) % float(b)
print('Результат деления по модулю:', l)